name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    needs: qa

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Docker Login - Azure Container Registry
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}

    - name: Build e Push no Container Registry
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY#*/}:latest
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY#*/}:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY#*/}:$(date +%s)
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY#*/}